services:
  app:
    build:
      dockerfile: dev.Dockerfile
      context: .
      target: development
      restart: unless-stopped
    volumes:
      - ./src:/app/src
    ports:
      - ${VISIR_HOST_PORT}:${PORT}